import type { Metadata } from "next";
import { Clicker_Script, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/components/modules/Footer/Footer";
import Subscribe from "@/components/templates/Subscribe/Subscribe";

const clicker_script = Clicker_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-script",
});
const playfair_display = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clicker_script.variable} ${playfair_display.variable} font-sans flex flex-col min-h-screen justify-between`}
      >
        {children}

        <footer>
          <Subscribe/>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
